name: Trigger CircleCi job

on:
  push:
      branches:
        - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Trigger exiting circleci job
        uses: zivkaziv/circleci-trigger-github-action@master
        with:
          token: ${{ secrets.CIRCLE_CI_TOKEN }}
          org: TwiztedDesign
          repo: videoflow-automation
          branch: master